NVIDIA/edk2-nvidia

Platform/NVIDIA/Jetson/Jetson.dsc.inc
Silicon/NVIDIA/Include/Library/MceAriLib.h
Silicon/NVIDIA/Include/Library/TegraPlatformInfoLib.h
Silicon/NVIDIA/Library/MceAriLib/MceAriLib.c
Silicon/NVIDIA/Library/TegraCacheMaintenanceLib/TegraCacheMaintenanceLib.c
Silicon/NVIDIA/Library/TegraCacheMaintenanceLib/TegraCacheMaintenanceLib.inf

Arm cache maintenance api may not be able to reach SCF. Rely on
explicit mce ari calls.
Change-Id: I96da9a8e4649299045a467fcd05f85eed289d678
Reviewed-on: https://git-master.nvidia.com/r/c/tegra/bootloader/uefi/edk2-nvidia/+/2709823
Reviewed-by: svc-sw-mobile-l4t <svc-sw-mobile-l4t@nvidia.com>
GVS: Gerrit_Virtual_Submit

fix: t234: clean invalidate caches to scf level using mce ari

---

Silicon/NVIDIA/Drivers/EqosDeviceDxe/EqosDeviceDxe.c

Need to shutdown network activity at UEFI exit especially in the case of ACPI boot.
As the memory set aside for that may be reclaimed by operating system.
Bug 3680336
Signed-off-by: Jeff Brasen <jbrasen@nvidia.com>
Change-Id: I834741497e32d074af53a146921a031eb8dcd8e1
Reviewed-on: https://git-master.nvidia.com/r/c/tegra/bootloader/uefi/edk2-nvidia/+/2728620
Reviewed-by: svcacv <svcacv@nvidia.com>
Reviewed-by: svc-sw-mobile-l4t <svc-sw-mobile-l4t@nvidia.com>
GVS: Gerrit_Virtual_Submit

fix(eqos): EQoS DMA may be active at exit boot services 

---

Silicon/NVIDIA/Library/ConfigurationManagerLib/ConfigurationManagerGicLib.c
Silicon/NVIDIA/Library/ConfigurationManagerLib/ConfigurationManagerLib.inf

Add support for walking the GICR to find size.
Bug 3750428
Signed-off-by: Jeff Brasen <jbrasen@nvidia.com>
Change-Id: Iebbaba7948e8f82eb8c7edb290b0d46fd4273c7c
Reviewed-on: https://git-master.nvidia.com/r/c/tegra/bootloader/uefi/edk2-nvidia/+/2758675
Reviewed-by: svcacv <svcacv@nvidia.com>
Reviewed-by: Swatisri Kantamsetti <swatisrik@nvidia.com>
Tested-by: Rohit Khanna <rokhanna@nvidia.com>
GVS: Gerrit_Virtual_Submit

fix: Calculate redist size dynamically

---

Silicon/NVIDIA/Application/L4TLauncher/L4TLauncher.c

When switch rootfs slot, rootfs slot is not linked
with bootloader chain, set the rootfs slot to
variable BootChainOsOverride.
Signed-off-by: Russell Xiao <russellx@nvidia.com>

L4Tlauncher: set BootChainOsOverride when switch rootfs

---

Silicon/NVIDIA/Drivers/DefaultVariableDxe/DefaultVariableDxe.c
Silicon/NVIDIA/Drivers/DefaultVariableDxe/DefaultVariableDxe.inf
Silicon/NVIDIA/Library/PlatformBootOrderLib/PlatformBootOrderLib.c
Silicon/NVIDIA/Library/PlatformBootOrderLib/PlatformBootOrderLib.inf
Silicon/NVIDIA/Tegra/DeviceTree/BootOrderNvme.dts
Silicon/NVIDIA/Tegra/DeviceTree/BootOrderPxe.dts
Silicon/NVIDIA/Tegra/DeviceTree/BootOrderSata.dts
Silicon/NVIDIA/Tegra/DeviceTree/BootOrderUfs.dts
Silicon/NVIDIA/Tegra/DeviceTree/BootOrderUsb.dts
Silicon/NVIDIA/Tegra/DeviceTree/DeviceTree.inf

Add support for setting default boot order via a variable.
Currently supports class type options.
Future enhancement will add support for specifing the instance
of a device.
Variable that controls this is DefaultBootPriority and contains
a comma seperated string with the following values.
"scsi"     - SCSI devices
"usb"      - USB devices
"sata"     - SATA devices
"pxev4"    - IPv4 PXE boot
"httpv4"   - IPv4 HTTP boot
"pxev6"    - IPv6 PXE boot
"httpv6"   - IPv6 HTTP boot
"nvme"     - Nvme devices
"ufs"      - UFS devices
"sd"       - SD devices
"emmc"     - eMMC devices
"cdrom"    - CD/DVD drives
"boot.img" - Android style boot.img partition
Any entries that are not in the list will be left at the end of the
boot order.
If the variable is not found "boot.img,usb,sd,emmc,ufs" is used

feat: Variable based default boot order support

---

Silicon/NVIDIA/Library/FloorSweepingLib/FloorSweepingLib.c
Silicon/NVIDIA/Library/FloorSweepingLib/FloorSweepingLib.inf

Update thermal mappings to delete cooling device entries with deleted phandles, e.g. floorswept CPUs.
Signed-off-by: Bob Morgan <bobm@nvidia.com>

fix(t234): thermal floorsweeping support

---

Silicon/NVIDIA/Drivers/DefaultVariableDxe/DefaultVariableDxe.c
Silicon/NVIDIA/Drivers/DefaultVariableDxe/DefaultVariableDxe.inf
Silicon/NVIDIA/Drivers/TegraPlatformInit/TegraPlatformInitDxe.c
Silicon/NVIDIA/Drivers/TegraPlatformInit/TegraPlatformInitDxe.inf

Currently the PcdUserPhysicalPresence PCD is set to FALSE to prevent users from being able to modify secure-boot related settings via the UEFI Menu.
This works well on most platforms/SOCs where StandaloneMm image is present to manage the variables.
On AGX Xavier, which doesn't have StandaloneMm to manage variables setting this PCD to FALSE prevents enrolling default keys and enabling secure-boot via the Key Enrollment App.
To workaround this issue set the PhysicalPresence Pcd to TRUE for AGX Xavier Devices to allow the default keys to be enrolled, and when the next reboot is done.
Signed-off-by: Girish Mahadevan <gmahadevan@nvidia.com>

fix: Allow secure boot enablement on AGX Xavier platform

---

Silicon/NVIDIA/Library/FmpDeviceLib/TegraFmp.c

Ensure strings read from UEFI variables TegraPlatformSpec and TegraPlatformCompatSpec are null-terminated before using them.

fix: ensure termination of TnSpec variables

---

Platform/NVIDIA/NVIDIA.common.dsc.inc
Silicon/NVIDIA/Library/PlatformBootManagerLib/PlatformBm.c
Silicon/NVIDIA/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf
Silicon/NVIDIA/NVIDIA.dec

Change PlatformRegisterConsoles() to only call
EfiBootManagerUpdateConsoleVariable() for [ConOut|ErrOut|ConIn] on the first boot, instead of re-initializing those persistent variables on every boot. This is controlled by a new Boolean PCD PcdDoInitialConsoleRegistration.
This fixes Boot Menu console settings not persisting through reboots.
Fixes #38 
Signed-off-by: Aron Wong <awong@nvidia.com>

fix: Boot Menu console option settings

---

Platform/NVIDIA/Jetson/Jetson.dsc.inc

Update maximum capsule size reported by the
QueryCapsuleCapabilities UEFI RT service and
used by CapsuleApp.

fix: update max capsule size supported

---

Silicon/NVIDIA/Drivers/FwPartitionBlockIoDxe/FwPartitionBlockIoDxe.c

Install FwPartitionProtocol for BlockIo partitions found on SD devices in addition to eMMC devices.

fix: suport FW partitions on SD devices

---

.github/workflows/build.yml

python3.9 is now required by recent versions of stuart.

fix(github): Install python3.9 during github builds

---

.github/workflows/build.yml

When getting the BUILDID from the build log, be sure to take only one match. Additional matches become extra arguments to "mv".
Also, fix deprecation warning around set-output.  Migrate to using $GITHUB_OUTPUT as recommended.

fix(github): Fix packaging

---

.github/release-drafter.yml
.github/workflows/build.yml

Follow the edkrepo manifest from NVIDIA-Jetson to NVIDIA-Platforms. Also, fix the workflow for pull requests.
Signed-off-by: Jake Garver <jake@nvidia.com>

fix(github): Migrate to NVIDIA-Platforms

---

Silicon/NVIDIA/Library/TegraSerialPortLib/TegraSerialPortLib.c

In TegraSerialPortLib, silently ignore any pre-init calls, such as SerialPortWrite().  Otherwise, these calls could result in a crash. Better to ignore them, especially since we cannot report the failure yet (because serial hasn't been initialized).
When INFO logs were enabled, we hit an exception early in DxeCore.  This was caused by a call into SerialPortWrite() before SerialPortInitialize() had been called.  SerialPortWrite() attempted to dereference gSerialCompatibilityMap, which was still NULL.
Arguably, a library should never be logging during init.  But that's going to be hard to prevent.  Therefore, we're adding this guard instead.
Reviewed-by: Jeshua Smith <jeshuas@nvidia.com>
Reviewed-by: Jeff Brasen <jbrasen@nvidia.com>

fix: Guard against serial writes before serial init

---

Silicon/NVIDIA/Tegra/T194/Drivers/ConfigurationManager/ConfigurationManagerData/ConfigurationManagerDataDxe.c

The behavior of `UpdateSerialPortInfo` for the T234 differs from that of the T194. When all serial ports are disabled on the T234, DSDT is not patched with serial port info and the ConfigurationManager DXE resumes as normal. When this is the case on the T194, the error bubbles up to the top of ConfigurationManager's entrypoint, causing many further configuration tables to not be populated (SMBIOS being one of them).

fix(t194): Fix error with no serial ports configured on T194

---

Silicon/NVIDIA/Drivers/EqosDeviceDxe/EqosDeviceDxe.inf

This fixes a compile issue on versions of GCC 10.x or later that enable outline-atomics by default.  CompilerIntrinsicsLib supports many of these atomics, but not the ones in use by nvethernetrm.
Signed-off-by: Jake Garver <jake@nvidia.com>
Reviewed-by: Jeff Brasen <jbrasen@nvidia.com>

fix: Disable outline-atomics for nvethernetrm

---

.github/workflows/build.yml

The github.head_ref is only defined for pull requests.  We should be using github.ref instead.
github.head_ref was working for some branches because it became an empty string.  That led to the default combo being used, which is "main".

fix(github): Correct branch builds in workflow

---

.github/workflows/build.yml

The github.head_ref is only defined for pull requests.  We should be using github.ref_name instead.
github.head_ref was working for some branches because it became an empty string.  That led to the default combo being used, which is "main".

fix(github): Correct branch builds in workflow, take 2

---

Platform/NVIDIA/Jetson/Jetson.dsc.inc

set pcd to tell about extra kernel command line parameters expected on jetson platforms for android style boot.

chore: allow extra characters for command line

---

Silicon/NVIDIA/Drivers/FvbDxe/FvbDxe.c

FTW writes from the variable driver could span block boundaries as the driver won't divvy up the transaction like it does for FVB writes.
Add logic to the FtwWrite to split the writes if they span block boundaries.

fix: split ftw writes if they span blocks r35.6

---

Platform/NVIDIA/NVIDIA.common.dsc.inc
Silicon/NVIDIA/Drivers/AcpiDtbSsdtGenerator/AcpiDtbSsdtGenerator.c
Silicon/NVIDIA/Drivers/NvDisplayControllerDxe/NvDisplayControllerDxe.c
Silicon/NVIDIA/Drivers/NvidiaConfigDxe/NvidiaConfigDxe.c
Silicon/NVIDIA/Drivers/NvidiaConfigDxe/NvidiaConfigDxe.inf
Silicon/NVIDIA/Drivers/NvidiaConfigDxe/NvidiaConfigHii.h
Silicon/NVIDIA/Drivers/NvidiaConfigDxe/NvidiaConfigHii.vfr
Silicon/NVIDIA/NVIDIA.dec

Resolve 2 issues with acpi boot on Orin.
1. Free before use issue that was reported in issue #116 in the AcpiSsdtDtbGenerator driver. This driver is refactored in later versions and this fix does not apply to later releases.
2. Backport leaving the internal display clocks on in ACPI boot from main branch.

Resolve ACPI boot issues on AGX Orin

---

Silicon/NVIDIA/Drivers/FvbNorFlashDxe/VarIntCheck.c
Silicon/NVIDIA/Include/Library/StandaloneMmOpteeDeviceMem.h
Silicon/NVIDIA/Library/NvVarIntLibrary/NvVarIntLibrary.c

Bug Fixes to the VarStore Integrity module.
- Bug fix in the erase logic. Bug in LBA compute that impacts some code-paths.
- Bug fix in the logic to compute secure-boot hashes. This will manifest as a device crash if the secureboot keys are enrolled at runtime and the device is rebooted.

Varintfixes r36.4.3 updates

---

.github/workflows/build.yml

upload-artifact@v3 is no longer allowed in github actions.

chore(github): Migrate to upload-artifact@v4

---

Platform/NVIDIA/Kconfig

Enable the Auto mode of SOC display hand-off by default.
Reviewed-by: Jake Garver <jake@nvidia.com>
Tested-by: Jake Garver <jake@nvidia.com>

fix: switch default value of PcdSocDisplayHandoffMode to Auto

---

.github/workflows/build.yml

This platform is not ready yet and shouldn't be built as part of the github CI.  It was mistakenly added.

chore(github): Don't build StandaloneMmJetson yet

---

Silicon/NVIDIA/Drivers/AndroidBootDxe/AndroidBootDxe.c
Silicon/NVIDIA/Drivers/AndroidBootDxe/AndroidBootDxe.h

During normal boot, if boot.img doesn't contain the ramdisk, attempt to load from init_boot.img instead.

feat: add support for android init_boot

---

.github/workflows/build.yml

Rather than hardcode the list of images to build, loop through the defconfigs and build all of them.  We'll still need to hardcode the list of non-Kconfig images.

chore: Update github workflow to include new images
